name: Secrets and Security

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  use-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Uzyj sekretu
        env:
          TOKEN: ${{ secrets.API_TOKEN }}
        run: |
          echo "Dlugosc tokenu: ${#TOKEN}"
          echo "Proba bezpiecznego wyswietlenia: ${{ secrets.API_TOKEN }}"
