name: Secrets and Security

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  use-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Uzyj sekretu
        env:
          TOKEN: ${{ secrets.API_TOKEN }}
        # Bezpośrednie używanie polecenia echo na sekretach może spowodować, że hasło przypadkowo wycieknie do logów. 
        # Zdecydowanie bezpieczniej jest przekazywać wrażliwe dane jako zmienne środowiskowe env.
        run: |
          echo "Dlugosc tokenu: ${#TOKEN}"
          echo "Proba bezpiecznego wyswietlenia: ${{ secrets.API_TOKEN }}"
